# Generated by Django 4.2.11 on 2024-07-08 13:15

from django.db import migrations, models
import face_photo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('face_photo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='bg_image',
            field=models.ImageField(null=True, upload_to=face_photo_app.models.get_admin_background_upload_path),
        ),
    ]
