# Generated by Django 4.2.11 on 2024-07-22 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_photo_app', '0004_alter_addnewcustomer_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewcustomer',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='face_photo_app.customuser'),
        ),
    ]
